version: '3'

services:
  cat-food-app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - bundle-cache:/usr/local/bundle
